apiVersion: v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: fastapi
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: osvadev01/fast-api-ml-project:latest
          ports:
            - containerPort: 8000