apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  namespace: streamlit
  labels:
    app: streamlit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: osvadev01/streamlit-app:latest
          ports:
            - containerPort: 8501
          env:
            - name: API_URL
              value: "http://model-service.model.svc.cluster.local:8000"